name: Clipboard Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-linux-amd64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: |
          cmake src -D TEST=1
          cmake --build .
          sudo cmake --install .

          echo "Blah!" > dummy.txt
          mkdir dummydir
          echo "Blah!" > dummydir/foo.txt

          clipboard copy dummy.txt dummydir
          if [ ! -f /tmp/Clipboard/0/dummy.txt ]; then
            echo did not copy file
            exit 1
          fi
          if [ ! -f /tmp/Clipboard/0/dummydir/foo.txt ]; then
            echo did not copy directory
            exit 1
          fi

          mkdir dummydir2
          cd dummydir2
          clipboard paste
          if [ ! -f dummy.txt ]; then
            echo did not paste file
            exit 1
          fi
          if [ ! -f dummydir/foo.txt ]; then
            echo did not paste file in directory
            exit 1
          fi
          echo "Bleh" | clipboard
          if [ ! -f /tmp/Clipboard/0/clipboard.txt ]; then
            echo did not copy contents piped in
            exit 1
          fi

          clipboard paste > dummy.txt
          contents=$(cat dummy.txt)
          if [ "$contents" != "Bleh" ]; then
            echo "contents: $contents"
            exit 1
          fi

          cd ..
          rm -rf dummydir2

          clipboard copy1 dummy.txt dummydir
          if [ ! -f /tmp/Clipboard/1/dummy.txt ]; then
            echo did not copy file into cb 1
            exit 1
          fi
          if [ ! -f /tmp/Clipboard/1/dummydir/foo.txt ]; then
            echo did not copy directory into cb 1
            exit 1
          fi

          mkdir dummydir2
          cd dummydir2
          clipboard paste1
          if [ ! -f dummy.txt ]; then
            echo did not paste file from cb 1
            exit 1
          fi
          if [ ! -f dummydir/foo.txt ]; then
            echo did not paste file in directory from cb 1
            exit 1
          fi
          echo "Bleh" | clipboard copy1
          if [ ! -f /tmp/Clipboard/1/clipboard.txt ]; then
            echo did not copy contents piped in to cb 1
            exit 1
          fi

          echo "Test passed"