name: Clipboard Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-linux-amd64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: |
          cmake src -D TEST=1
          cmake --build .
          sudo cmake --install .
          export TMPDIR=/tmp
          bash tests/test_files.sh
          bash tests/test_redirection.sh
          bash tests/test_files_and_redirection.sh
  test-macos-amd64:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          brew install gcc
          cmake src -D CMAKE_CXX_COMPILER=g++-12 -D TEST=1
          cmake --build .
          cmake --install .
          bash tests/test_redirection.sh
  test-windows-amd64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        shell: bash
        run: |
          cmake src -D TEST=1
          cmake --build .
          echo $TMPDIR
          echo $HOME