name: Clipboard Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-linux-amd64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: |
          cmake src -D TEST=1
          cmake --build .
          sudo cmake --install .
          bash test.sh
  test-macos-amd64:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          cmake src -D TEST=1
          cmake --build .
          csrutil disable
          sudo cmake --install .
          bash test.sh